######################################################################
# Automatically generated by qmake (3.0) Sun Jun 12 13:35:02 2016
######################################################################

TEMPLATE = app
TARGET = msgpacker
CONFIG -= qt
INCLUDEPATH += .

# Input
HEADERS += \
    baseencode.h
SOURCES += main.c \
    baseencode.c
